spring:
  application:
    name: emovision
  datasource:
    url: "jdbc:postgresql://localhost:5432/emovision?autoReconnect=true"
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    validation-query: select 1;
    max-active: 100
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 5MB
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
server:
  port: 8080
  servlet:
    context-path: /api
token:
  signing:
    key: "59fb3552f2b260aae4021ec9f35533d22c15cf57467ee720a990d2de70dcb5f0"
